name: Build and Push Docker Image

on:
# Disabling since keeps running out of System RAM on the GitHub runner
#  push:
#    branches:
#      - main
  pull_request:
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: /home/runner/work/crew-chief-autovoicepack/crew-chief-autovoicepack

    permissions:
      contents: write  # Allows writing to the repository

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 20000
          swap-size-mb: 512
          temp-reserve-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check disk space
        run: df -h

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.7.0
        with:
          push: true
          tags: ghcr.io/cktlco/crew-chief-autovoicepack:latest
          # no-cache: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

