name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: write  # Allows writing to the repository

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.7.0
        with:
          push: true
          tags: ghcr.io/cktlco/crew-chief-autovoicepack:latest
          no-cache: true
          #cache-from: type=gha
          #cache-to: type=gha,mode=max

